<a href="https://colab.research.google.com/github/tasnimislam/sesssional/blob/master/sessional1numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

ARRAYS

In [5]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0]
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 3]


In [9]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0 ,0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [11]:
b=np.array([[1,2,3],[4,5]])
print(b.shape)
print(b[0 ,0], b[0, 1], b[1, 0])

(2,)


IndexError: ignored

In [12]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [13]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [14]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [0]:
d=np.eye(2)


In [16]:
print(d)

[[1. 0.]
 [0. 1.]]


In [18]:
e=np.random.random((2,2))
print(e)

[[0.37695306 0.93819964]
 [0.30973538 0.59059089]]
